### ISSUE TITLE
Pgbouncer cannot connet to server

### ISSUE THREAD

**Issue by segundoBhumia** [brainsam/pgbouncer#18]
Hi,
I cannot connect to local postgres container 10.4 with pgbouncer 1.8.1. The Pooler Error is "pgbouncer cannot connect to server". 

Following is my config:

docker-compose file:
```yaml
version: '3.2'
services:
  pg:
    image: postgres:10.4-alpine
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data
      - type: volume
        source: pg-config
        target: /usr/local/share/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"

  pgb:
    image: brainsam/pgbouncer:1.8.1
    environment:
      DB_HOST: 127.0.0.1
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - type: volume
        source: pgb-config
        target: /etc/pgbouncer
    restart: unless-stopped
    ports:
      - "6432:6432"
    depends_on:
      - pg

volumes:
  pg-data:
  pg-config:
  pgb-config:
```
pgbouncer.ini file:
```ini
[databases]
* = host=localhost port=5432 user=postgres password=postgres

[pgbouncer]
# Generic settings
pool_mode = session
listen_addr = *
listen_port = 6432
auth_type = any
ignore_startup_parameters = extra_float_digits
#logfile = /var/log/pgbouncer/pgbouncer.log
#pidfile = /var/run/pgbouncer/pgbouncer.pid
#unix_socket_dir = /var/run/postgresql
#unix_socket_mode = 0777
log_connections = 1
log_disconnections = 1
log_pooler_errors = 1

# Log settings
admin_users = postgres

# Connection sanity checks, timeouts

# TLS settings
server_tls_sslmode = disable
client_tls_sslmode = disable
```
postgresql.conf listen address is set to "*"

I would really appreciate if someone can help.

Thanks
