### ISSUE TITLE
Can not connect to PgBouncer by timeout

### ISSUE THREAD

**Issue by binhbt** [brainsam/pgbouncer#24]
When i run in docker-compose  and access to my database via Dbeaver. Its connect timeout. 
pgbouncer_1            | 2020-04-08 05:18:17.585 UTC [1] LOG S-0x559298d8f0e0: postgres/postgres@(bad-af):0 closing because: connect timeout (age=15s)

```
postgres:
    image: postgres:11.7
    environment:
      POSTGRES_USER: postgres     # define credentials
      POSTGRES_PASSWORD: postgres # define credentials
      POSTGRES_DB: postgres       # define database
    ports:
      - 5432:5432   
    # command: postgres -c 'max_connections=10000' -c 'shared_buffers=512MB'
  # Postgres database.
  pgbouncer:
    image: brainsam/pgbouncer:1.12.0
    environment:
      DB_HOST: postgres
      DB_USER: postgres           # define credentials
      DB_PASSWORD: postgres       # define credentials
      DB_port: 5432
      POOL_MODE: transaction
      DEFAULT_POOL_SIZE: 56
      MAX_CLIENT_CONN: 10000
    # volumes:
    #   - ./pgbouncer:/etc/pgbouncer
    links:
      - postgres:postgres
    ports:
      - 6433:6432 
```
