### ISSUE TITLE
Access to the pgbouncer admin console

### ISSUE THREAD

**Issue by ghost** [brainsam/pgbouncer#9]
This is probably more of a question than an issue. It may be that it's not possible or desirable, but is there any way of accessing the PGBouncer [admin console](https://pgbouncer.github.io/usage.html#admin-console) whilst running this image?

For info I'm running the latest 1.7.2 image.

**Comment by larkost** [comment]
I know this is a little late, but.... Yes you can, you just need to export the port so that you can connect to it. How to do this depends on how you are launching this Docker container.

If you are just using this one container then just add `--publish 5432:5432` to your `docker run` command. This will map port 5432 from the container to your host locally. Then you can:
`pgsql -h localhost` (plus your authentication settings) to connect to it.

If you are using `docker-compose` then make it something like this:
```
version: "2.1"
services:
  pgbouncer:
    image: brainsam/pgbouncer
    environment:
      DB_HOST: POSTGRES_HOST
      DB_USER: POSTGRES_USERNAME
      DB_PASSWORD: POSTGRES_PASSWORD
      LISTEN_PORT: 5432    
    ports:
      - "5432:5432"
```

The Dockerfile could be modified to make this a little more obvious. Someone (maybe me) could play around with adding:
```EXPOSE ${LISTEN_PORT:-5432}```
To see if that is dynamic at runtime. That would allow for using `--publish-all` and at least make the port show up in `docker ps`.
